# Word Exploration 
Notebook to clean the NLP Disaster Tweets dataset. These are also preprocessing steps for model training.

In [1]:
# Read necessary modules
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np 
import os
import tensorflow as tf
import re
import nltk
from nltk.corpus import stopwords
from collections import Counter

2025-11-20 08:05:16.303359: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
# Set working directory
os.chdir('/home/54b3e09d-d775-4c65-93b7-67c241d43466/5511_PR_week4')

In [3]:
# Read dataset
train_df = pd.read_csv('train.csv')
train_df

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1
...,...,...,...,...,...
7608,10869,NaN,NaN,Two giant cranes holding a bridge collapse int...,1
7609,10870,NaN,NaN,@aria_ahrary @TheTawniest The out of control w...,1
7610,10871,NaN,NaN,M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...,1
7611,10872,NaN,NaN,Police investigating after an e-bike collided ...,1
7612,10873,NaN,NaN,The Latest: More Homes Razed by Northern Calif...,1

In [4]:
# Function to remove integers from selected columns
def remove_numbers(x):
    return re.sub(r'\d+', '', x)

In [5]:
# Remove integers from column text
train_df['text'] = train_df['text'].apply(remove_numbers)
train_df

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,", people receive #wildfires evacuation orders ...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1
...,...,...,...,...,...
7608,10869,NaN,NaN,Two giant cranes holding a bridge collapse int...,1
7609,10870,NaN,NaN,@aria_ahrary @TheTawniest The out of control w...,1
7610,10871,NaN,NaN,M. [: UTC]?km S of Volcano Hawaii. http://t.co...,1
7611,10872,NaN,NaN,Police investigating after an e-bike collided ...,1
7612,10873,NaN,NaN,The Latest: More Homes Razed by Northern Calif...,1

In [6]:
# function to remove stopwords from nltk corpus from strings
def basic_clean(x):
  """
  A simple function to clean up the data. All the words that
  are not designated as a stop word is then lemmatized after
  encoding and basic regex parsing are performed.
  """
  stops = set(stopwords.words('english'))
  words = re.sub(r'[^\w\s]', '', x).lower().split()
  return [word for word in words if word not in stops]

In [7]:
# apply function basic_clean to column text
train_df['text'] = train_df['text'].apply(basic_clean)

# apply lambda function to put column text in right format
train_df['text'] = train_df['text'].apply(lambda x: ', '.join(x))
train_df

,id,keyword,location,text,target
0,1,NaN,NaN,"deeds, reason, earthquake, may, allah, forgive...",1
1,4,NaN,NaN,"forest, fire, near, la, ronge, sask, canada",1
2,5,NaN,NaN,"residents, asked, shelter, place, notified, of...",1
3,6,NaN,NaN,"people, receive, wildfires, evacuation, orders...",1
4,7,NaN,NaN,"got, sent, photo, ruby, alaska, smoke, wildfir...",1
...,...,...,...,...,...
7608,10869,NaN,NaN,"two, giant, cranes, holding, bridge, collapse,...",1
7609,10870,NaN,NaN,"aria_ahrary, thetawniest, control, wild, fires...",1
7610,10871,NaN,NaN,"utckm, volcano, hawaii, httptcozdtoydebj",1
7611,10872,NaN,NaN,"police, investigating, ebike, collided, car, l...",1
7612,10873,NaN,NaN,"latest, homes, razed, northern, california, wi...",1

In [8]:
# Put all tokens from train_df.text in a list
list_total = []

for i in train_df.text.str.split():
    for j in i:
        list_total.append(j)

In [9]:
# Every token in list_total with its frequency
Countertje = Counter(list_total)

In [10]:
# Rank the tokens by frequency in Countertje.
Countertje_rk = Countertje.most_common()

# from token 2.674 every token appears at most four times in list_total.
Countertje_rk[2673:][:6]

[('wrecked', 5),
 ('school', 4),
 ('rockyfire,', 4),
 ('springs,', 4),
 ('street', 4),
 ('tampa,', 4)]

### Conclusion
If the tokens are ranked by frequency token #2674 is the first token that appears at most four times. Therefore, unless noted otherwise, the maximum vocabulary size is 2.673.